[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["frederic@lenquette.com"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.1.27"